@startuml
autonumber

actor "HelpDesk Manager" as HDM
participant "System" as UI

activate HDM
HDM --> UI : Register a Catalogue
activate UI
    UI --> HDM : Requests necessary credentials for Catalogue
deactivate UI
HDM --> UI : Inserts the data
activate UI
UI --> HDM : displayCatalogueInfo
deactivate UI

@enduml