@startuml
autonumber

actor "HelpDesk Manager" as HDM

participant "RegisterServiceUI" as UI
participant "RegisterServiceController" as CTRL
participant "ServiceBuilder" as CB
participant "Service:Service" as CC
participant "PersistenceContext" as PC
participant "RepositoryFactory" as RF


database "ServiceRepository" as CR

HDM --> UI : Register a Service
activate UI
    UI -> CTRL : create
    UI --> HDM : Requests necessary credentials for Service
deactivate UI

HDM --> UI : Inserts the data
activate UI
    UI -> CTRL : Service = newService(ServiceCode code, ServiceTitle title, \nServiceIcon icon, ServiceDescriptio description)
    activate CTRL
        CTRL -> CB: create
        activate CB
        deactivate CB

        CTRL -> CB: setCatalogue(catalogue)
        activate CB
        deactivate CB

note over CTRL, CB : Sets the rest of the information


        CTRL -> CB: createService()
        activate CB
                CB -> CC: create(ServiceCode code, ServiceTitle title, \nServiceIcon icon, ServiceDescriptio description)
                CC -> CB: Service
                CB -> CTRL: Service
        deactivate CB

        CTRL -> PC:
        activate PC
        note over PC, CR : can create an repository in memory or JPA
         PC->RF: create
         PC->CTRL: factory

        deactivate PC

        CTRL->RF:Services()
        activate RF
        RF->CR:create
        RF->CTRL:ServiceRepository()
        deactivate RF

        CTRL->CR:save(Service)

        CTRL->UI:Service
    deactivate CTRL

    UI --> HDM : displayServiceInfo
deactivate UI


@enduml
