@startuml
'https://plantuml.com/class-diagram

class RegisterAnColaboratorUI {
}

class RegisterAnColaboratorController {
registerColaborator();
}

class Colaborator {
SystemUser user;
MecanographicNumber mecanographicNumber;
Name name;
Address address;
BirthDate birthDate;
Evaluation evaluation;
Contact contact;
}

class MecanographicNumber{
String mecanographicNumber;
}

class Name{
String name;
}

class Address{
String street;
String city;
}

class BirthDate{
Date birthDate;
}

class Evaluation{
long evaluation;
}

class Contact{
long contact
}

class SystemUser{
Username username;
Password password;
Name name;
EmailAddress email;
RoleSet roles;
}

RegisterAnColaboratorUI -> RegisterAnColaboratorController
RegisterAnColaboratorController -> Colaborator

SystemUser -> Colaborator
Colaborator -> MecanographicNumber
Colaborator -> Name
Colaborator -> Address
Colaborator -> BirthDate
Colaborator -> Evaluation
Colaborator -> Contact

@enduml