@startuml
'https://plantuml.com/class-diagram

class ListCataloguesUI {
}

class MyCataloguesController {
+registerForm();
}

class CataloguePrinter{
+visit();
}



ListCataloguesUI -> MyCataloguesController
MyCataloguesController -> CataloguePrinter

@enduml