@startuml
autonumber

actor "Colaborator" as C
participant "System" as UI

activate C
C --> UI : Wants to create a form
activate UI
    UI --> C : Requests necessary information for Form
deactivate UI
C --> UI : Inserts the data
activate UI
UI --> C : displayFormInfo
deactivate UI

@enduml